source $HOME/.bashrc

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

##
# Your previous /Users/steve/.bash_profile file was backed up as /Users/steve/.bash_profile.macports-saved_2016-02-09_at_20:42:33
##

# MacPorts Installer addition on 2016-02-09_at_20:42:33: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.

