#!/usr/bin/bash

# path
PATH=$PATH:$HOME/Applications/activator-1.3.0-minimal:$HOME/Applications/scala-2.11.5/bin:/opt/ImageMagick/bin/:$HOME/Library/android/sdk/platform-tools:$HOME/Library/android/sdk/tools
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/Library/Android/sdk/tools/lib64

# imports
source $HOME/.git-prompt.sh

# default editor
#export EMACS="/Applications/Emacs.app/Contents/MacOS/Emacs"
export EMACS="/Applications/Emacs2.app/Contents/MacOS/Emacs"
export EDITOR="$EMACS -nw"
alias e="$EDITOR"
alias emacs="$EMACS"

# grep alias
g()
{
    egrep -I "$@" | egrep -v "\~|#.*#:"
}

# alias to open all the files in emacs that match the grep
ea()
{
    e $(g $@ | cut -d: -f1 | sort -u)
}

# 'll' alias
alias ll="ls -l"

# python path
export PYTHONPATH=".:/Library/Python/2.7/site-packages"

# git completion
source $HOME/.git-completion.bash

# git aliases
alias gs="git status"
alias gd="git diff"
__git_complete gd _git_diff
alias gl="git log"
__git_complete gl _git_log
alias gk="git checkout"
__git_complete gk _git_checkout
alias gb="git branch"
__git_complete gb _git_branch
alias ga="git add"
__git_complete ga _git_add
alias gc="git commit"
__git_complete gc _git_commit
alias gr="git rebase"
__git_complete gr _git_rebase
alias gf="git fetch -p"

#colors
BLUE="\[\033[1;34m\]"
YELLOW="\[\033[0;93m\]"
RED="\[\033[0;31m\]"
WHITE="\[\033[0;37m\]"

# prompt
GIT_PS1_SHOWDIRTYSTATE="true"
GIT_PS1_SHOWSTASHSTATE="true"
GIT_PS1_SHOWUNTRACKEDFILES="true"
GIT_PS1_SHOWUCOLORHINTS="true"
GIT_PS1_SHOWUPSTREAM="auto"
export PS1="${BLUE}[${YELLOW}\w${RED}\$(__git_ps1 \" (%s)\")${BLUE}]${WHITE} "

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# Gemfury authentication
export FURY_ENV="WWGJfnrStJtdTjS7zmxj"

# Get a list of all the rails files given a list of roots
rails_files_in_dir()
{
    find $1 | egrep "(Gemfile*)|\.(rb|haml|js|scss)$" | egrep -v "./db/migrate" | tac
}

rails_files()
{
    if [[ "$#" == 0 ]]; then
        rails_files_in_dir .
    else
        while [[ "$#" != "0" ]]; do
            find $1 | egrep "\.(rb|haml|js|scss)$"
            shift
        done
    fi
}

# Open emacs on a list of rails files for the given list of roots
er()
{
    e $(rails_files $*)
}

# date stuff
datel()
{
    date -r ${1:0:10}
}

dateu()
{
    date -ur ${1:0:10}
}
